name: GIT CI - PHP + BIN
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  php-bin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
      - run: |
          php -l run_install.php
          ls -lh install.BIN run_install.php
          php run_install.php --help || true
